// <auto-generated />
using System;
using CCC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CCC.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220323113837_SeedExpenseClaimData")]
    partial class SeedExpenseClaimData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CCC.Data.Model.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Title = "Develpment"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Title = "Hr"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Title = "Sales"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Title = "Support"
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "Test",
                            DepartmentId = 1,
                            Email = "Ahmed@ccc.com",
                            Name = "Ahmed"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "Test",
                            DepartmentId = 2,
                            Email = "Mohmmed@ccc.com",
                            Name = "Mohmmed"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Address = "Test",
                            DepartmentId = 3,
                            Email = "Ali@ccc.com",
                            Name = "Ali"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Address = "Test",
                            DepartmentId = 4,
                            Email = "Sanaa@ccc.com",
                            Name = "Sanaa"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Address = "Test",
                            DepartmentId = 1,
                            Email = "Raghd@ccc.com",
                            Name = "Raghd"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Address = "Test",
                            DepartmentId = 2,
                            Email = "Saja@ccc.com",
                            Name = "Saja"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Address = "Test",
                            DepartmentId = 3,
                            Email = "Tamer@ccc.com",
                            Name = "Tamer"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Address = "Test",
                            DepartmentId = 4,
                            Email = "Nasim@ccc.com",
                            Name = "Nasim"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Address = "Test",
                            DepartmentId = 1,
                            Email = "Basil@ccc.com",
                            Name = "Basil"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Address = "Test",
                            DepartmentId = 2,
                            Email = "Marwa@ccc.com",
                            Name = "Marwa"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Address = "Test",
                            DepartmentId = 1,
                            Email = "Marwan@ccc.com",
                            Name = "Marwan"
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.ExpenseClaim", b =>
                {
                    b.Property<int>("ExpenseClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseClaimId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("ExpenseClaimId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ExpenseClaims");

                    b.HasData(
                        new
                        {
                            ExpenseClaimId = 1,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2709),
                            Description = "Test",
                            EmployeeId = 1,
                            Status = 2,
                            Total = 2000m
                        },
                        new
                        {
                            ExpenseClaimId = 2,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2715),
                            Description = "Test2",
                            EmployeeId = 1,
                            Status = 2,
                            Total = 2000m
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.ExpenseClaimDetail", b =>
                {
                    b.Property<int>("ExpenseClaimDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenseClaimDetailId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("ExpenseClaimDetailId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("ExpenseClaimDetails");

                    b.HasData(
                        new
                        {
                            ExpenseClaimDetailId = 1,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2804),
                            Description = "Meals",
                            ExpenseClaimId = 1,
                            Total = 1200m
                        },
                        new
                        {
                            ExpenseClaimDetailId = 2,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2808),
                            Description = "Taxi",
                            ExpenseClaimId = 1,
                            Total = 500m
                        },
                        new
                        {
                            ExpenseClaimDetailId = 3,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2809),
                            Description = "Tools Rental",
                            ExpenseClaimId = 1,
                            Total = 300m
                        },
                        new
                        {
                            ExpenseClaimDetailId = 4,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2810),
                            Description = "Meals",
                            ExpenseClaimId = 2,
                            Total = 1200m
                        },
                        new
                        {
                            ExpenseClaimDetailId = 5,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2811),
                            Description = "Taxi",
                            ExpenseClaimId = 2,
                            Total = 500m
                        },
                        new
                        {
                            ExpenseClaimDetailId = 6,
                            Date = new DateTime(2022, 3, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2813),
                            Description = "Tools Rental",
                            ExpenseClaimId = 2,
                            Total = 300m
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeaveId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Leaves");

                    b.HasData(
                        new
                        {
                            LeaveId = 1,
                            EmployeeId = 1,
                            From = new DateTime(2022, 3, 22, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2608),
                            LeaveTypeId = 1,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 28, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2615)
                        },
                        new
                        {
                            LeaveId = 2,
                            EmployeeId = 2,
                            From = new DateTime(2022, 3, 13, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2621),
                            LeaveTypeId = 2,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 21, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2621)
                        },
                        new
                        {
                            LeaveId = 3,
                            EmployeeId = 3,
                            From = new DateTime(2022, 3, 3, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2622),
                            LeaveTypeId = 3,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 18, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2623)
                        },
                        new
                        {
                            LeaveId = 4,
                            EmployeeId = 4,
                            From = new DateTime(2022, 3, 19, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2624),
                            LeaveTypeId = 4,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 15, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2624)
                        },
                        new
                        {
                            LeaveId = 5,
                            EmployeeId = 5,
                            From = new DateTime(2022, 3, 22, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2625),
                            LeaveTypeId = 5,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 21, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2626)
                        },
                        new
                        {
                            LeaveId = 6,
                            EmployeeId = 6,
                            From = new DateTime(2022, 3, 31, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2628),
                            LeaveTypeId = 6,
                            Note = "Test note",
                            To = new DateTime(2022, 4, 8, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2628)
                        },
                        new
                        {
                            LeaveId = 7,
                            EmployeeId = 7,
                            From = new DateTime(2022, 3, 28, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2629),
                            LeaveTypeId = 7,
                            Note = "Test note",
                            To = new DateTime(2022, 4, 7, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2630)
                        },
                        new
                        {
                            LeaveId = 8,
                            EmployeeId = 8,
                            From = new DateTime(2022, 3, 22, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2631),
                            LeaveTypeId = 8,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 17, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2631)
                        },
                        new
                        {
                            LeaveId = 9,
                            EmployeeId = 1,
                            From = new DateTime(2022, 3, 20, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2632),
                            LeaveTypeId = 9,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 17, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2633)
                        },
                        new
                        {
                            LeaveId = 10,
                            EmployeeId = 2,
                            From = new DateTime(2021, 12, 13, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2635),
                            LeaveTypeId = 10,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 3, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2635)
                        },
                        new
                        {
                            LeaveId = 11,
                            EmployeeId = 3,
                            From = new DateTime(2022, 1, 2, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2636),
                            LeaveTypeId = 1,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 28, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2636)
                        },
                        new
                        {
                            LeaveId = 12,
                            EmployeeId = 4,
                            From = new DateTime(2021, 12, 23, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2637),
                            LeaveTypeId = 2,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 30, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2638)
                        },
                        new
                        {
                            LeaveId = 13,
                            EmployeeId = 5,
                            From = new DateTime(2021, 12, 27, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2639),
                            LeaveTypeId = 3,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 30, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2639)
                        },
                        new
                        {
                            LeaveId = 14,
                            EmployeeId = 6,
                            From = new DateTime(2022, 3, 9, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2640),
                            LeaveTypeId = 4,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 17, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2640)
                        },
                        new
                        {
                            LeaveId = 15,
                            EmployeeId = 11,
                            From = new DateTime(2021, 12, 25, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2641),
                            LeaveTypeId = 5,
                            Note = "Test note",
                            To = new DateTime(2022, 2, 7, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2642)
                        },
                        new
                        {
                            LeaveId = 16,
                            EmployeeId = 8,
                            From = new DateTime(2022, 2, 7, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2643),
                            LeaveTypeId = 6,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 1, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            LeaveId = 17,
                            EmployeeId = 9,
                            From = new DateTime(2022, 1, 30, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2644),
                            LeaveTypeId = 7,
                            Note = "Test note",
                            To = new DateTime(2022, 2, 22, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2644)
                        },
                        new
                        {
                            LeaveId = 18,
                            EmployeeId = 5,
                            From = new DateTime(2021, 10, 24, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2646),
                            LeaveTypeId = 8,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 2, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2647)
                        },
                        new
                        {
                            LeaveId = 19,
                            EmployeeId = 4,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2648),
                            LeaveTypeId = 9,
                            Note = "Test note",
                            To = new DateTime(2021, 12, 13, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2648)
                        },
                        new
                        {
                            LeaveId = 20,
                            EmployeeId = 3,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2649),
                            LeaveTypeId = 10,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 28, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2650)
                        },
                        new
                        {
                            LeaveId = 21,
                            EmployeeId = 2,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2651),
                            LeaveTypeId = 1,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 18, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2651)
                        },
                        new
                        {
                            LeaveId = 22,
                            EmployeeId = 1,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2652),
                            LeaveTypeId = 2,
                            Note = "Test note",
                            To = new DateTime(2021, 12, 28, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2652)
                        },
                        new
                        {
                            LeaveId = 23,
                            EmployeeId = 7,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2653),
                            LeaveTypeId = 3,
                            Note = "Test note",
                            To = new DateTime(2022, 1, 29, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2654)
                        },
                        new
                        {
                            LeaveId = 24,
                            EmployeeId = 8,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2654),
                            LeaveTypeId = 4,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 8, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2655)
                        },
                        new
                        {
                            LeaveId = 25,
                            EmployeeId = 10,
                            From = new DateTime(2021, 10, 14, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2656),
                            LeaveTypeId = 5,
                            Note = "Test note",
                            To = new DateTime(2022, 3, 22, 11, 38, 36, 963, DateTimeKind.Utc).AddTicks(2656)
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<string>("Title")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            Title = "Privilege Leave"
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            Title = "Earned Leave"
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            Title = "Annual Leave"
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            Title = "Casual Leave"
                        },
                        new
                        {
                            LeaveTypeId = 5,
                            Title = "Sick Leave"
                        },
                        new
                        {
                            LeaveTypeId = 6,
                            Title = "Maternity Leave"
                        },
                        new
                        {
                            LeaveTypeId = 7,
                            Title = "Marriage Leave"
                        },
                        new
                        {
                            LeaveTypeId = 8,
                            Title = "Paternity Leave"
                        },
                        new
                        {
                            LeaveTypeId = 9,
                            Title = "Leave Without Pay"
                        },
                        new
                        {
                            LeaveTypeId = 10,
                            Title = "Loss of Pay"
                        });
                });

            modelBuilder.Entity("CCC.Data.Model.Employee", b =>
                {
                    b.HasOne("CCC.Data.Model.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CCC.Data.Model.ExpenseClaim", b =>
                {
                    b.HasOne("CCC.Data.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CCC.Data.Model.ExpenseClaimDetail", b =>
                {
                    b.HasOne("CCC.Data.Model.ExpenseClaim", "ExpenseClaim")
                        .WithMany("ExpenseClaimDetails")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("CCC.Data.Model.Leave", b =>
                {
                    b.HasOne("CCC.Data.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCC.Data.Model.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("CCC.Data.Model.ExpenseClaim", b =>
                {
                    b.Navigation("ExpenseClaimDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
